server:
  port: 8081
logging:
  level:
    org:
      springframework: INFO
    com:
      mkyong: INFO
      zaxxer: DEBUG
    root: ERROR
spring:
  datasource:
    url: jdbc:h2:mem:pms
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolZZZ
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2